# Generated by Django 5.2.13 on 2026-05-09 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Nissan', 'نیسان'), ('Pickup_nissan', 'نیسان کمپرسی'), ('Roomy_nissan', 'نیسان اتاقی'), ('Khorman', 'خاور'), ('Truck', 'کامیون'), ('Trailer', 'تریلی'), ('Pickup_truck', 'وانت')], max_length=50, verbose_name='نوع وسیله')),
                ('driver_city', models.CharField(choices=[('Dezful', 'دزفول'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز'), ('Isfahan', 'اصفهان'), ('Mashhad', 'مشهد'), ('Tabriz', 'تبریز'), ('Ahvaz', 'اهواز'), ('Karaj', 'کرج'), ('Qom', 'قم'), ('Kermanshah', 'کرمانشاه'), ('Rasht', 'رشت'), ('Zahedan', 'زاهدان'), ('Hamadan', 'همدان'), ('Yazd', 'یزد'), ('Ardabil', 'اردبیل'), ('Bandar_Abbas', 'بندرعباس'), ('Arak', 'اراک'), ('Urmia', 'ارومیه'), ('Sanandaj', 'سنندج'), ('Gorgan', 'گرگان'), ('Babol', 'بابل'), ('Qazvin', 'قزوین'), ('Zanjan', 'زنجان'), ('Khorramabad', 'خرم\u200cآباد'), ('Bushehr', 'بوشهر'), ('Sari', 'ساری'), ('Birjand', 'بیرجند'), ('Ilam', 'ایلام'), ('Yasuj', 'یاسوج'), ('Shahrekord', 'شهرکرد'), ('Bojnord', 'بجنورد')], max_length=50, verbose_name='شهر فعالیت')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('within_city', 'درون شهری'), ('intercity', 'برون شهری')], default='within_city', max_length=20, verbose_name='نوع مسیر')),
                ('cargo_type', models.CharField(max_length=100, verbose_name='نوع بار')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='وزن (تن)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='مبدا')),
                ('pickup_address', models.TextField(verbose_name='آدرس دقیق بارگیری')),
                ('dropoff_location', models.CharField(max_length=200, verbose_name='مقصد')),
                ('dropoff_address', models.TextField(verbose_name='آدرس دقیق تخلیه')),
                ('pickup_date_shamsi', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ بارگیری (شمسی)')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='ساعت بارگیری')),
                ('pickup_datetime_gregorian', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان (میلادی)')),
                ('expected_delivery_date_shamsi', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تحویل (شمسی)')),
                ('expected_delivery_time', models.TimeField(blank=True, null=True, verbose_name='ساعت تحویل')),
                ('required_vehicle', models.CharField(choices=[('Nissan', 'نیسان'), ('Pickup_nissan', 'نیسان کمپرسی'), ('Roomy_nissan', 'نیسان اتاقی'), ('Khorman', 'خاور'), ('Truck', 'کامیون'), ('Trailer', 'تریلی'), ('Pickup_truck', 'وانت')], max_length=50, verbose_name='وسیله مورد نیاز')),
                ('city', models.CharField(choices=[('Dezful', 'دزفول'), ('Tehran', 'تهران'), ('Shiraz', 'شیراز'), ('Isfahan', 'اصفهان'), ('Mashhad', 'مشهد'), ('Tabriz', 'تبریز'), ('Ahvaz', 'اهواز'), ('Karaj', 'کرج'), ('Qom', 'قم'), ('Kermanshah', 'کرمانشاه'), ('Rasht', 'رشت'), ('Zahedan', 'زاهدان'), ('Hamadan', 'همدان'), ('Yazd', 'یزد'), ('Ardabil', 'اردبیل'), ('Bandar_Abbas', 'بندرعباس'), ('Arak', 'اراک'), ('Urmia', 'ارومیه'), ('Sanandaj', 'سنندج'), ('Gorgan', 'گرگان'), ('Babol', 'بابل'), ('Qazvin', 'قزوین'), ('Zanjan', 'زنجان'), ('Khorramabad', 'خرم\u200cآباد'), ('Bushehr', 'بوشهر'), ('Sari', 'ساری'), ('Birjand', 'بیرجند'), ('Ilam', 'ایلام'), ('Yasuj', 'یاسوج'), ('Shahrekord', 'شهرکرد'), ('Bojnord', 'بجنورد')], max_length=50, verbose_name='شهر بارگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار راننده'), ('assigned', 'اختصاص داده شده'), ('in_progress', 'در حال حمل'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_loads', to='loads.driver')),
            ],
            options={
                'verbose_name': 'بار',
                'verbose_name_plural': 'بارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.driver')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='loads.load')),
            ],
        ),
    ]
